sudo: required
dist: xenial

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION='3.3'

install:
  - sudo apt install docker.io
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - echo "127.0.0.1  test.ch" | sudo tee -a /etc/hosts
  - echo "127.0.0.1  wordpress.test.ch" | sudo tee -a /etc/hosts
  - echo "127.0.0.1  owncloud.test.ch" | sudo tee -a /etc/hosts
  - docker-compose ./docker-compose.yml up -d
  - sleep 15

#script: ./scripts/test.sh

after_script:
  - docker rm -f $(docker ps -a -q)
  - docker volume prune -f