sudo: required
dist: xenial

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION='3.3'

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin 

before_script:
  - echo "127.0.0.1  test.ch" | sudo tee -a /etc/hosts
  - echo "127.0.0.1  wordpress.test.ch" | sudo tee -a /etc/hosts
  - echo "127.0.0.1  owncloud.test.ch" | sudo tee -a /etc/hosts
  - docker-compose ./docker-compose.yml up -d
  - sleep 15

script: ./scripts/test.sh

after_script:
  - docker rm -f $(docker ps -a -q)
  - docker volume prune -f