Vagrant.configure(2) do |config|

  config.vm.define "dns" do |dns|
    dns.vm.box = "ubuntu/xenial64"
    dns.vm.hostname = "dns01"
    dns.vm.network "private_network", ip: "10.0.0.10"
      dns.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "dns01"
      end
      dns.vm.synced_folder ".", "/var/www/html/Fileshare"
      dns.vm.provision "shell", path: "dns.sh"
  end

  config.vm.define "ca" do |ca|
    ca.vm.box = "ubuntu/xenial64"
    ca.vm.hostname = "ca01"
    ca.vm.network "private_network", ip:"10.0.0.13"
      ca.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "ca01"
      end
      ca.vm.synced_folder ".", "/var/www/html/Fileshare"
      ca.vm.provision "shell", path: "ca.sh"
  end

  config.vm.define "database" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "10.0.0.11"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "db01"
      end
      db.vm.synced_folder ".", "/var/www/html/Fileshare"
      db.vm.provision "shell", path: "db.sh"
  end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"10.0.0.12"
      web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
      web.vm.network "forwarded_port", guest:443, host:4343, auto_correct: true
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "web01"
      end
      web.vm.synced_folder ".", "/var/www/html/Fileshare"
      web.vm.provision "shell", path: "web.sh"
  end
     
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/xenial64"
    client.vm.hostname = "client01"
    client.vm.network "private_network", ip:"10.0.0.50"
      client.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "client01"
        vb.gui = "true"
      end
      client.vm.synced_folder ".", "/var/www/html/Fileshare"
      client.vm.provision "shell", path: "client.sh"
  end

  config.vm.define "extclient" do |extclient|
    extclient.vm.box = "ubuntu/xenial64"
    extclient.vm.hostname = "extclient01"
    extclient.vm.network "private_network", ip:"40.0.0.50"
      extclient.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "extclient01"
        vb.gui = "true"
      end
      extclient.vm.synced_folder ".", "/var/www/html/Fileshare"
      extclient.vm.provision "shell", path: "extclient.sh"
  end

end