Vagrant.configure(2) do |config|

  config.vm.define "dhcp" do |dhcp|
    dhcp.vm.box = "ubuntu/xenial64"
    dhcp.vm.hostname = "dhcp01"
    dhcp.vm.network "private_network", ip: "10.0.0.10"
      dhcp.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      dhcp.vm.synced_folder ".", "/var/www/html/Fileshare"
      dhcp.vm.provision "shell", path: "dhcp.sh"
  end

  config.vm.define "database" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "10.0.0.11"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      db.vm.synced_folder ".", "/var/www/html/Fileshare"
      db.vm.provision "shell", path: "db.sh"
  end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"10.0.0.12"
      web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
      web.vm.network "forwarded_port", guest:443, host:4343, auto_correct: true
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      web.vm.synced_folder ".", "/var/www/html/Fileshare"
      web.vm.provision "shell", path: "web.sh"
  end
     
  
  config.vm.define "client" do |client|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "client01"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      web.vm.synced_folder ".", "/var/www/html/Fileshare"
      web.vm.provision "shell", path: "client.sh"
  end

end